name: check-commit-title

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-commit-title:
    runs-on: ubuntu-latest
    name: Check commit title
    steps:
      - uses: actions/checkout@v3
      - name: Check commit tile
        id: check-commit-title
        run: |
          echo "title of the latest commit: $(git show -s --format='%s')"
          echo "title of grep of the latest commit: $(git show -s --format='%s' | grep '\[no-publish\]')"
          echo "title of the second latest commit: $(git show -s --format='%s' HEAD~1)"
          if git show -s --format='%s' | grep '\[no-publish\]'; then
            echo 'need-publish=false' >> $GITHUB_OUTPUT
            echo "'[no-publish]' is found in commit title, no need to publish Docker image"
          else
            echo 'need-publish=true' >> $GITHUB_OUTPUT
            echo "Need to publish Docker image: "
          fi
 
