name: Super-Linter

on:
  workflow_dispatch:

jobs:
  super-lint:
    name: Lint code base
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [ubuntu-18.04]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Super-Linter
        uses: github/super-linter@v3.17.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
