name: variable-test

on: 
  push:
  workflow_dispatch:

jobs:
  generate-variable:
    runs-on: ubuntu-latest 
    name: generate variable
    outputs:
      boolean-value: ${{ steps.generate-variable.outputs.boolean-value }}
    steps:
      - name: generate variable
      - id: generate-variable
      - run: |
          echo 'boolean-value=true' >> $GITHUB_OUTPUT


  check-value:
    needs: generate-variable
    runs-on: ubuntu-latest
    steps:
      - if: ${{ needs.generate-variable.outputs.boolean-value }}
          echo "boolean-value has value"
      - if: ${{ ! needs.generate-variable.outputs.boolean-value }}
          echo "boolean-value has no value"
